### PR TITLE
Feat  contact us modal

### PR DESCRIPTION
**Pull request by marwaghassa**
Thank you modal added

### CODE REVIEW

**Comment by osamaakb** [comment]
can you please provide more explanation what does this PR fix?

**Comment by marwaghassa** [comment]
Screenshot (21)
i added this modal that shows up when we click on the submit button

**Comment by osamaakb** [comment]
for some reason it is not showing after I click submit

**Comment by osamaakb** [comment]
the image isn't showing and the form modal stays visible after submitting, but I will merge anyway for the sake of time

**Review by osamaakb — APPROVED** [review]

**Pull request merged**
